ALTER TABLE hr.locations CHANGE `STREET_ADDRESS` address VARCHAR(40);
ALTER TABLE hr.regions CHANGE `REGION_NAME` region VARCHAR(25);
ALTER TABLE hr.countries CHANGE `COUNTRY_NAME` country VARCHAR(40);
